### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by apbarratt** [home-assistant/intents#1000]
I know it seems silly to some, but I've always said please and thank you to my various assistants.

HA's assist was happy to accept "Turn on the bathroom light, please" but seemed flummoxed when I put "Thank you muchly."
I figured I was probably overcomplicating things so tried just "Thank you" but even that seemed to upset it 😅

**Comment by svarthvitt** [comment]
The following words are removed from commands given in English:
skip_words:
  - "please"
  - "can you"

You could potentially add "Thank you" and "muchly" to the list.

**Comment by synesthesiam** [comment]
I think this is a good idea for the future: essentially sentences that are not meant to trigger an intent. Not something we have time for now, unfortunately :slightly_frowning_face:
