### ISSUE TITLE
Intent isn't recognized unless I specify "light"

### ISSUE THREAD

**Issue by nesati** [home-assistant/intents#1026]
![uživatel: zhasni světlo Obývák
Home Assistant:  Světlo bylo vypnuto
uživatel:  zhasni Obývák
Home Assistant:  Omlouvám se, ale nerozuměl jsem tomu](https://user-images.githubusercontent.com/59739799/219157048-fa87c33d-eb9d-4d16-8cf1-d8dec75020e5.png)

The verb (*zhasni*) implies I am referring to a light (*světlo*), making it unnecessary to specify, but the command won't work unless it is specified. I've tried searching through other issues and didn't find anything, so it might be a Czech-specific issue. It's also possible that the issue lies in my setup as *Obývák* is both the name of an area and a light within that area. Any help would be appreciated.

**Comment by schizza** [comment]
> ![uživatel: zhasni světlo Obývák Home Assistant: Světlo bylo vypnuto uživatel: zhasni Obývák Home Assistant: Omlouvám se, ale nerozuměl jsem tomu](https://user-images.githubusercontent.com/59739799/219157048-fa87c33d-eb9d-4d16-8cf1-d8dec75020e5.png)
> 
> The verb (_zhasni_) implies I am referring to a light (_světlo_), making it unnecessary to specify, but the command won't work unless it is specified. I've tried searching through other issues and didn't find anything, so it might be a Czech-specific issue. It's also possible that the issue lies in my setup as _Obývák_ is both the name of an area and a light within that area. Any help would be appreciated.

Zkus přejmenovat oblast `obývák` na zkusit to znovu. Podle mě to padá to obecného zapni. A ještě zkontrolovat jestli světlo `obývák` je opravdu entita `light`.

**Comment by schizza** [comment]
> > ![uživatel: zhasni světlo Obývák Home Assistant: Světlo bylo vypnuto uživatel: zhasni Obývák Home Assistant: Omlouvám se, ale nerozuměl jsem tomu](https://user-images.githubusercontent.com/59739799/219157048-fa87c33d-eb9d-4d16-8cf1-d8dec75020e5.png)
> > The verb (_zhasni_) implies I am referring to a light (_světlo_), making it unnecessary to specify, but the command won't work unless it is specified. I've tried searching through other issues and didn't find anything, so it might be a Czech-specific issue. It's also possible that the issue lies in my setup as _Obývák_ is both the name of an area and a light within that area. Any help would be appreciated.
> 
> Zkus přejmenovat oblast `obývák` na zkusit to znovu. Podle mě to padá to obecného zapni. A ještě zkontrolovat jestli světlo `obývák` je opravdu entita `light`.

ping @nesati

**Comment by nesati** [comment]
> Zkus přejmenovat oblast `obývák` na zkusit to znovu. Podle mě to padá to obecného zapni. A ještě zkontrolovat jestli světlo `obývák` je opravdu entita `light`.

Když přejmenuju oblast Obývák, nefunguje ani jeden z příkazů. Entita Obývák má id `light.obyvak`.

**Comment by schizza** [comment]
> > Zkus přejmenovat oblast `obývák` na zkusit to znovu. Podle mě to padá to obecného zapni. A ještě zkontrolovat jestli světlo `obývák` je opravdu entita `light`.
> 
> Když přejmenuju oblast Obývák, nefunguje ani jeden z příkazů. Entita Obývák má id `light.obyvak`.

@nesati 
ještě pozor na velká písmena, vše je case-sensitive

```

  - name: "Obývák"
    id: living_rooom

entities:
  - name: Obývák
    id: light.obyvak
    area: living_room
    attributes:
      device_class: light
    state:
      in: "rozsvíceno"
      out: "on"
```

mě to v simulaci jde:
```
--sentence "rozsviť Obývák"
{
  "text": "rozsviť Obývák",
  "match": true,
  "intent": "HassTurnOn",
  "slots": {
    "name": "Obývák",
    "domain": "light"
  },
  "context": {
    "domain": "light"
  },
  "response_key": "light",
  "response": "Světlo obývák bylo zapnuto"
}
```

**Comment by nesati** [comment]
Ještě jsem zkusil přejmenovat `media_player.living_room_tv` z `Obývák` na něco jiného, ale ani to nepomohlo.

> ještě pozor na velká písmena, vše je case-sensitive

Zkusil jsem přidat `obývák` (s malým o) jako alias a vyzkoušel velké i malé o v příkazu a nic nepomohlo.

Jediné co pomůže je přejmenovat oblast zpět na `Obývák`a pak funguje alespoň příkaz `zhasni světlo Obývák` viz screenshot.

> ```
> --sentence "rozsviť Obývák"
> {
>   "text": "rozsviť Obývák",
>   "match": true,
>   "intent": "HassTurnOn",
>   "slots": {
>     "name": "Obývák",
>     "domain": "light"
>   },
>   "context": {
>     "domain": "light"
>   },
>   "response_key": "light",
>   "response": "Světlo obývák bylo zapnuto"
> }
> ```

Lze se nějak podívat na tenhle výsledek parsování pro moji instanci Home Assistanta?

**Comment by schizza** [comment]
Fixed in #1051.
