### ISSUE TITLE
No intents were loaded for language - Both Chinese

### ISSUE THREAD

**Issue by bluefoxlee** [home-assistant/intents#1104]
According to log, it seems Home Assistant core use zh-hans for S.Chinese and zh-hant for T.Chinese.
On the other hand Intents use zh-cn/zh-tw/(zh-hk) for those languages. With cause loading issue.

```
Logger: homeassistant.components.conversation.default_agent
Source: components/conversation/default_agent.py:301
Integration: 語音互動 (documentation, issues)
First occurred: 2023年2月23日 11:29:10 (3 occurrences)
Last logged: 24:22:08

No intents were loaded for language: zh-Hant
No intents were loaded for language: zh-Hans

```

**Comment by al-one** [comment]
```
Logger: custom_components.conversation.default_agent
Source: custom_components/conversation/default_agent.py:117
Integration: 语音对话
First occurred: 09:03:35 (1 occurrences)
Last logged: 09:03:35

No intents were loaded for language: zh-Hans
```

@synesthesiam  Should we use `zh-Hans` instead of `zh-cn`.

**Comment by synesthesiam** [comment]
We're discussing ways to make this work now. We chose to use zh-cn, etc. in the intents repo because dialect mattered more than just traditional vs. simplified Chinese.

The problem is that HA's list of languages is different than those in the intents repo now :/

**Comment by al-one** [comment]
Is it possible to select different languages depending on the country/area in the configuration of the HA.

```python
if language == 'zh-Hans':
  language = 'zh-cn'
elif language == 'zh-Hant':
  if hass.config.country == 'HK':
    language = 'zh-hk'
  elif hass.config.country == 'TW':
    language = 'zh-tw'
```

**Comment by bluefoxlee** [comment]
I am not a programmer, can not provide much opinions from coding perspective.
However, I would like to suggest to consider the solution in the long term way, as voice assistant will be a long term and huge project for Home Assistant. not just match language code to pass the issue. 

As we can see from [issue 1013](https://github.com/home-assistant/intents/issues/1013) and [discussion 1196](https://github.com/home-assistant/intents/discussions/1196), perhaps the better way to deal it will be separate Ui language and Assist (Voice in the future). user will be able to one language as UI, and speaking language in another. just like Chinese as UI, but mandarin, cantonese in Assist. 

BTW, W3C, IANA also define to use zh-hans-cn, zh-hant-hk, zh-hant-tw as the region subtag if HA team consider to use the zh-hans/zh-hant subtag.

**Comment by sasukebinbin** [comment]
Some addon for Siri assist.
After I put zh-cn into custom_sentences and rename it to zh-Hans. 
Assist in HA works great using Simplified Chines.
But Siri assist still can work in English only 
After test out, I found the issue was the language set in Assist on the shorcut. I can only chooese Simplified Chinese not zh-Hans. 
So as a workaround I used call service with conversation.process and set language to zh-Hans in dict.
It works great.

**Comment by ritech** [comment]
> 

yes ,conversation.process could be work

but you can't listen home assistant feedback voice

**Comment by psychopasss** [comment]
> Some addon for Siri assist. After I put zh-cn into custom_sentences and rename it to zh-Hans. Assist in HA works great using Simplified Chines. But Siri assist still can work in English only After test out, I found the issue was the language set in Assist on the shorcut. I can only chooese Simplified Chinese not zh-Hans. So as a workaround I used call service with conversation.process and set language to zh-Hans in dict. It works great.

Could you explain the procedure in detail?

**Comment by sasukebinbin** [comment]
> 

I have a post in a Chinese forum you can check. 
https://bbs.hassbian.com/thread-19983-1-1.html

**Comment by sasukebinbin** [comment]
> > Some addon for Siri assist. After I put zh-cn into custom_sentences and rename it to zh-Hans. Assist in HA works great using Simplified Chines. But Siri assist still can work in English only After test out, I found the issue was the language set in Assist on the shorcut. I can only chooese Simplified Chinese not zh-Hans. So as a workaround I used call service with conversation.process and set language to zh-Hans in dict. It works great.
> 
> Could you explain the procedure in detail?

I have a post in a Chinese forum you can check.
https://bbs.hassbian.com/thread-19983-1-1.html

**Comment by sasukebinbin** [comment]
> > 
> 
> yes ,conversation.process could be work
> 
> but you can't listen home assistant feedback voice

For Chinese, even in HA GUI, the reply is <silence>. I think the reply not build for Chinese yet.

**Comment by bluefoxlee** [comment]
It seems 2023.5.x has the issue. So I will close this issue report for now. 
Thank you. @al-one @synesthesiam
