### ISSUE TITLE
Inconsistant results from HassGetState intents

### ISSUE THREAD

**Issue by TheFes** [home-assistant/intents#1108]
The HassGetState intents are getting inconsistant results

For Dutch the `<schakelaar>` expansion rule matches with `schakelaar[s]`, `plug[gen]` and `switch[es]`

![image](https://user-images.githubusercontent.com/28803438/221017922-8831896c-4f30-4f98-873b-702a5a8dad2a.png)

> Me: Hoeveel schakelaars staan aan? (how many `schakelaars` are on)
> Assist: 34
> 
> Me: Hoeveel pluggen staan aan? (how many `pluggen` are on)
> Assist: 23
> 
> Me: Hoeveel switches staan aan? (how many `switches` are on)
> Assist: 17
> 
> Me: Welke schakelaars staan aan? (which `schakelaars` are on)
> Assist: FlorsiCam Alarm_Tone, FlorisCam Infrared_Light, FlorisCam Sound and 5 more
> 
> Me: Welke pluggen staan aan? (which `pluggen` are on)
> Assist: 43PUS6704/12 Screen state, BW Plug 16 - Ketel, FlorisCam Alarm_Tone en nog 11
> 
> Me: Welke switches staan aan? (which `switches` are on)
> Assist: FlorisCam Alarm_Tone, FlorisCam Infrared_Light, FlorisCam Sound en nog 4

So there is no consistancy in the total reported number of switches which are on.
Also when I switch between pluggen/switches/schakelaars the number of items differs each time

**Comment by synesthesiam** [comment]
Great catch, thank you! The fix is needed on the HA side: https://github.com/home-assistant/core/pull/88683

When putting the translated state names in before rendering responses, I didn't realize I was actually *overwriting* the state. I had assumed I was working with a copy :man_facepalming:

**Comment by TheFes** [comment]
Okay, I'll test (what looks like to be a temporarily patch) when the next beta lands.
