### ISSUE TITLE
Arabic language support

### ISSUE THREAD

**Issue by Ahmed-farag36** [home-assistant/intents#112]
Hello,
firstly, thank you so much for this awesome work, and I want to contribute to add Arabic language and be assigned as a leader.

**Comment by synesthesiam** [comment]
Great! I've added some empty Arabic templates to the repository :+1:

**Comment by Ahmed-farag36** [comment]
Nice I have forked the repo, ran the setup script and added Arabic language.
Now I will start working.
Should I close this issue now?

**Comment by balloob** [comment]
Let's close it when the first PR lands 👍

**Comment by synesthesiam** [comment]
Discussion: https://github.com/home-assistant/intents/discussions/334
