### ISSUE TITLE
Set default area/location to trigger action

### ISSUE THREAD

**Issue by duhow** [home-assistant/intents#1141]
Given the "assistant" is set to a default location (eg. bedroom),
saying `turn on the light` without more details, should get the current **area** location and replace with it.

I'm guessing changes are needed in both the [home-assistant/intents](https://github.com/home-assistant/intents) parser and the [core](https://github.com/home-assistant/core).

Is this tracked somewhere?

**Comment by synesthesiam** [comment]
Some pieces for this are already in place. The `requires_context` portion of an intent can require an `area` without it being named. A satellite will then pass in a context like `{ "area": "bedroom"}` with its call to `conversation/process`

**Comment by duhow** [comment]
I'm setting this to done as should be implemented with:

```yaml
requires_context:
  area:
    slot: true
```
