### ISSUE TITLE
How many is returning count one higher than actual

### ISSUE THREAD

**Issue by blacknell** [home-assistant/intents#1213]
When I ask 'How many lights are on' or 'Which lights are on' it returns one more than correct. The reason seems to be that there is a light group for these rooms (created in Zigbee2MQTT).

Example
`Which lights are on` -> `Kitchen Lights and Kitchen Table Lights`
`How many lights are on` -> `2`

Kitchen Lights is a group comprising all the lights in the kitchen.

I don't think the count should include a group as clearly the answer should be `Kitchen Table Lights` and `1`

**Comment by TheFes** [comment]
There is currently nothing built in to exclude groups.
In the future you will be able to choose yourself which entities to expose to Assist. So you can then choose to exclude the group. Other people might choose to exclude the individual entities.

**Comment by blacknell** [comment]
OK. Sounds good.
