### ISSUE TITLE
Support for Slovak language

### ISSUE THREAD

**Issue by TomasTal** [home-assistant/intents#135]
I would love to help. My time is limited (because of my work and family), but if you need someone for the slovak translations or something other with that i can help. I would try my best because HA is great and you are too.

I have no previous experience. However, I am determined and hardworking.
And I can admit if I couldn't do something to 100% satisfaction.

**Comment by synesthesiam** [comment]
Any contribution would be appreciated :slightly_smiling_face: 
Please coordinate with @x15pa3ck15x and @MartinBucko

**Comment by matusk** [comment]
@TomasTal , @MartinBucko I'd be happy to help you.

**Comment by TomasTal** [comment]
> 

You can contact me on taligatomas@gmail.com

**Comment by synesthesiam** [comment]
Discussion continued here: https://github.com/home-assistant/intents/discussions/395
