### ISSUE TITLE
Support for Slovak language

### ISSUE THREAD

**Issue by nemo-df** [home-assistant/intents#137]
I want to help with the development of the Ukrainian language

**Comment by MartinBucko** [comment]
Hi, I will like to help with Slovak language. Thanks.

✌️🙂👍

**Comment by synesthesiam** [comment]
@nemo-df  please coordinate with @skynetua for Ukrainian.

@MartinBucko please coordinate with @x15pa3ck15x

**Comment by rici44** [comment]
Hi. I can help with Slovak. Thx :)

**Comment by havrancek** [comment]
I can help with Slovak too.

**Comment by synesthesiam** [comment]
Great! Discussion is continued here: https://github.com/home-assistant/intents/discussions/395
