### ISSUE TITLE
Version metadata is not getting updated

### ISSUE THREAD

**Issue by mweinelt** [home-assistant/intents#1417]
The version in the pyproject.toml has not been updated since the late April release. This is for some reason not an issue on the pypi sdist, but I thought I'd still mention that. Another solution to this could be [setuptools-scm](https://github.com/pypa/setuptools_scm/), that relies on git metadata (e.g. tags) to determine the correct version.

https://github.com/home-assistant/intents/blob/main/package/pyproject.toml#L7

**Comment by synesthesiam** [comment]
Packaging has been moved here: https://github.com/home-assistant/intents-package/
