### ISSUE TITLE
homeassistant_HassTurnOn intent file shouldn't include light sentences

### ISSUE THREAD

**Issue by svelho-personal** [home-assistant/intents#1444]
homeassistant_HassTurnOn is targeting lights/switches

```
      - sentences:
          - "<turn> on <name> [light[s]|switch[es]]"
          - "[<turn>] <name> [light[s]|switch[es]] [to] on"
          - "activate <name> [light[s]|switch[es]]"
```

Then some domains are getting excluded from the match
```
        excludes_context:
          domain:
            - binary_sensor
            - cover
            - lock
            - scene
            - script
            - sensor
```

The exclusion list doesn't include all domains (or any future domain additions).
For example, "turn on livingroom light" will turn on "livingroom" climate domain device, since "climate" domain isn't excluded. Same can happen with other domain devices.

<img width="209" alt="image" src="https://github.com/home-assistant/intents/assets/29729268/18646536-3cc9-44fc-8320-85e0da5858ea">

More specific sentences for each domain must be in the respective domain file (light_HassTurnOff.yaml), where the specific domain is targeted in "requires_context" or overwritten with "slots".

From the above I suggest removing all specific lights sentences from homeassistant_HassTurnOn and homeassistant_HassTurnOff

**Comment by tetele** [comment]
@svelho-personal #1446 should cover it, right?

**Comment by sevelho** [comment]
@tetele yes, seems perfect. Thanks!
Do you know if/how these type of changes get propagated to other languages? Must be manual? I need same update in PT

**Comment by tetele** [comment]
It's a manual process. @joaorgoncalves and @nikito7 are [language leaders](https://developers.home-assistant.io/docs/voice/intent-recognition/supported-languages/) for PT, EN is just a guideline.
