### ISSUE TITLE
Wrong entity prioritized when names conflict

### ISSUE THREAD

**Issue by taha-yassine** [home-assistant/intents#1457]
I have a "living room" zone with some lights. The sentence "turn on the living room lights" turns on the climate entity with the same name.
![image](https://github.com/home-assistant/intents/assets/40228615/3eee408c-d57a-4375-b9f0-98587e501216)
I suspect the problem comes from the fact that for some reason the matching seems to prioritize the entity name over the "lights" word. When I change the zone's name to "main room" and run the same sentence, it works as expected.
![image](https://github.com/home-assistant/intents/assets/40228615/3274b225-5893-4095-955e-8fe7706f4717)

**Comment by TheFes** [comment]
Already fixed in #1446
Will be included in the 2023.8 release
