### ISSUE TITLE
Add/Delete shopping list items with assistant

### ISSUE THREAD

**Issue by adocampo** [home-assistant/intents#1468]
I would like to start using the shopping list with Assistant. My idea is to add or delete items via voice, so when I'm on the supermarket, I can check the shopping list.

I've readed the documentation regarding the Assistant, but I cannot see how can I use variables in order to say for example:
 - Add eggs to the shopping list (or just "add eggs")

Is there any way to do it?

**Comment by tetele** [comment]
Adding items to shopping lists was done in #1466 and will be available in HA 2023.8
Deleting items through voice is a little risky, I think. If the STT engine misunderstands you, you might end up with some items you didn't want removed.
[Completing items](https://www.home-assistant.io/integrations/shopping_list/#service-shopping_listcomplete_item) from a shopping list will be assessed later on.

**Comment by adocampo** [comment]
> Adding items to shopping lists was done in #1466 and will be available in HA 2023.8 
That's great!

> Deleting items through voice is a little risky, I think. If the STT engine misunderstands you, you might end up with some items you didn't want removed.
I'm using right now alexa and its shopping list, and it works great deleting items, even when you have duplicate items, it deletes just the newer one, not all occurrences.

> [Completing items](https://www.home-assistant.io/integrations/shopping_list/#service-shopping_listcomplete_item) from a shopping list will be assessed later on.
That will be great, as well.

Thank you.

**Comment by adocampo** [comment]
> Deleting items through voice is a little risky, I think. If the STT engine misunderstands you, you might end up with some items you didn't want removed.

FYI: I've just deleted via voice an item from alexa, and it does NOT delete de item, it just mark as checked.
