### ISSUE TITLE
Proper releases?

### ISSUE THREAD

**Issue by hugobloem** [home-assistant/intents#1492]
Would it be possible to have the releases published as releases? Currently releases are hidden within the branches/tags making it difficult to see what has been introduced from release to release. Publishing these changes as releases makes it easier for people to see what has been added/changed.

**Comment by davefx** [comment]
Now that we are having releases, it would be great if we get some kind of notice some days before a release is published in order to bring translations up to date before the release.

**Comment by tetele** [comment]
...or a release calendar would also help

**Comment by hugobloem** [comment]
Perhaps a beta version? Then there's no commitment to release a specific feature by a set date.

**Comment by frenck** [comment]
Intents are shipped in Home Assistant Core. Any actual release to stable is thus bound to the Core release schedule and cycle.

Core has a beta, which is documented as well. Feel free to join that.

**Comment by davefx** [comment]
Oh, that's good to know, @frenck . 

So the missing point here would be knowing when exactly the snapshot of the Intents repository is taken to be shipped in HA Core, and what branch/release is used for this. 

Is it synchronized again for every HA Core Beta release and/or stable releases? 

We just want to know to be aware of what needs to be done related to translations and when we need to do it!
Thanks a lot!

**Comment by tetele** [comment]
@davefx there's [a script](https://github.com/home-assistant/intents/blob/main/script/package) that takes the `main` branch and packages a compilation of the sentences. Upon release, that package also gets pushed [to pypi](https://pypi.org/project/hassil/), but I think that's a manual process.

Once it gets to pypi, it is listed as [a dependency in HA core](https://github.com/home-assistant/core/blob/381ebf3e53d18cd801efb6e3b9bbf3159d18f9a5/requirements_all.txt#L1024), from where it is installed using pip. Obviously, like any dependency, its version [is bumped](https://github.com/home-assistant/core/pulls?q=is%3Apr+is%3Aclosed+bump+intents) when new releases appear.
