### ISSUE TITLE
Option to add a fallback intent

### ISSUE THREAD

**Issue by edurenye** [home-assistant/intents#1499]
Right now, if you do not have an intent that handles a sentence it will fallback to `_common > responses > errors > no_intent` and say "Sorry, I couldn't understand that".

Would be great to be able to add an intent to use as a fallback so it can be used in automations.

So for example we could use no_intent fallback to send the sentence to service that could be connected to a privatGPT server and get back the answer to the user.

Not sure how this could be implemented.

I know there is a component that let allows you to generate text responses using OpenAI's GPT-3 model. So this could also be used as a service there.

This issue is about having the fallback intent, nothing else.

**Comment by edurenye** [comment]
The component I was talking about: https://github.com/Hassassistant/openai_response

**Comment by tetele** [comment]
I think that pipeline chaining (i.e. if a pipeline fails, forward the entire initial request to another fallback pipeline) is on the roadmap, somewhere. Either way, this is not an issue for the intents repo, but for HA core.

@synesthesiam please transfer the issue if you think it's the case.

**Comment by edurenye** [comment]
Where can I see the roadmap?

And in core I couldn't find any issue related to this: https://github.com/home-assistant/core/issues

**Comment by tetele** [comment]
> Where can I see the roadmap?

Maybe "roadmap" is too big of a word. There were some discussions between intent maintainers about this particular thing at some point. I don't know of any public "roadmap" but maybe @jlpouffier is interested in publishing one at some point.

**Comment by edurenye** [comment]
Would be nice to have this, so I created a feature request for it in the forum: https://community.home-assistant.io/t/pipeline-chaining-or-fallback-intent/606175
