### ISSUE TITLE
Ukrainian language support

### ISSUE THREAD

**Issue by znack14** [home-assistant/intents#155]
Support for the Ukrainian language is very important. We really need an assistant in our language.  This will be the first assistant in Ukrainian history
I am ready to be a volunteer in this project in my free time from the war :)

**Comment by skynetua** [comment]
I've started doing it, work is in progress. You can review already added sentences and suggest changes if needed.

**Comment by denysdovhan** [comment]
Sign me in. I would gladly contribute to Ukrainian corpus.

**Comment by synesthesiam** [comment]
@skynetua would you like to be the Ukrainian language leader?
