### ISSUE TITLE
[ALL LANGUAGES]Wrong target when light and cover with the same name

### ISSUE THREAD

**Issue by Uriziel01** [home-assistant/intents#1552]
Hi,
when there is intent that is matching domain cover ("<open> <name> [in <area>]") and there is a light with the exact name and no cover with given name it won't match, everything's fine. But if coincidentally there are both light AND cover with the same it can match the wrong one and even if the only sentence that can be natched is specific for covers it still targets the wrong entity (light instead of cover).

and even when used intent is using requires_context `domain: cover` and `response: cover` it still matched to a light.

![image](https://github.com/home-assistant/intents/assets/568207/840be3e8-2abe-4730-8ad9-783c4b1385fb)
![image](https://github.com/home-assistant/intents/assets/568207/d3f146b2-600d-4416-b871-2cd1e9f9c13a)

**Comment by Uriziel01** [comment]
I've also tested this when developing a PR for Polish language and got the exact same issue, wrong entity is targeted.

**Comment by v1k70rk4** [comment]
As I've noticed, if anything in any domain shares a name, only the first one is considered.

I have (had) three lamps named "big". When I asked to turn on the big lamp, only the kitchen one turned on (it was the first).

If I say turn on the big lamp in the living room, the command fails because it only sees the kitchen one. But if I ask to turn on the big kitchen lamp, it turns on without a word.

**Comment by tetele** [comment]
Possibly related https://github.com/home-assistant/core/issues/109868

**Comment by jlpouffier** [comment]
Yeah pretty sure it's going to be fixed in 2024.2.1. The fix is already done. Keep your bug open and test it again when the new dot release comes out. I wanted to have this fixed in the major release but spent too much time writing the bug and it was very late.

**Comment by v1k70rk4** [comment]
The problem has been solved. (At least for me), if not, feel free to reopen it.

**Comment by Uriziel01** [comment]
LGTM
