### ISSUE TITLE
Trouble finding error...[slovenian] sentences

### ISSUE THREAD

**Issue by andrejs2** [home-assistant/intents#1568]
Hi!

I do my best to translate sentences into Slovenian language and now I'm in a phase to test with python script:
`python3 -m script.intentfest parse --language sl --sentence 'vključi luč na terasi'`

I get this:
`{
  "text": "vključi luči na terasi",
  "match": false
}`

Since I have trouble with other sentences too, I assume there is some other issue...maybe with insufficient translations of other parts or cells...

Can someone point me towards the right direction? Maybe @spuljko since I used most of Croatian translations (which btw are working in test)? Or any other tip how to checklist the areas maybe?

Thank you in advance!

**Comment by tetele** [comment]
I don't know any Slovenian and you haven't provided enough info (regarding an actual commit) for me to actually give you a definitive answer, but with the help of Google Translate and considering that you're referring to one of your many pull requests as of late, I will assume that you don't have an area named `terasi` in your `_fixtures.yaml`, which causes the intent not to be recognized.

May I also recommend the [#devs_voice](https://discord.com/channels/330944238910963714/1054846248374505572) channel in the Discord server for such questions.

**Comment by spuljko** [comment]
You are using singular in test and sentence expects plural (luč|luči). You can change sentence like this

- "<vključi> (luč[i]|svetil(a|o)|razsvetljavo|svetilk(u|e)) (v|na) [sobi] <area>"

Pay attention to brackets, what is in square brackets is not requred in sentence, while expression in round brackets is required. More info here: https://developers.home-assistant.io/docs/voice/intent-recognition/template-sentence-syntax/

Also, please don't create pull request for every push and divide branches in more logical way - for example one for lights, one for covers etc. Name PR so that everyone can understand what is changed, like "[si] addded lights sentences". Don't put things from one PR to another, always start branch from main. 
More info here under Creating perfect PR: https://developers.home-assistant.io/docs/review-process/

Hope that helps, feel free to ask if you need anything else.

**Comment by spuljko** [comment]
> you don't have an area named `terasi` in your `_fixtures.yaml`, which causes the intent not to be recognized.
> 
Good point, I didn't check fixtures.

**Comment by andrejs2** [comment]
Thank you @tetele and @spuljko! Very helpful! I was checking sentences and not other files. I did work on files and sentences, I found `_fixtures.yaml` only in `tests` folder. 

If I run:

`python3 -m script.intentfest parse --language sl --sentence 'Vklopi luč v kuhinji'
`

I still get:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/github2/intents/script/intentfest/__main__.py", line 29, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/github2/intents/script/intentfest/__main__.py", line 24, in main
    return module.run()
           ^^^^^^^^^^^^
  File "/home/github2/intents/script/intentfest/parse.py", line 89, in run
    render_response(response_template, result, matched, unmatched)
  File "/home/github2/intents/shared/__init__.py", line 159, in render_response
    assert response_template, "Empty response template"
AssertionError: Empty response template
```
I corrected `_fixtures.yaml` like this:

```
language: sl
areas:
  - name: "spalnic(a|i|o)"
    id: bedroom
  - name: "garaž(a|i|o)"
    id: garage
  - name: "pisarn(a|i|o)|kabinet(a|u)"
    id: office
  - name: "balkon(u)"
    id: balcony
  - name: "teras(a|i|o)"
    id: terrace
  - name: "omar(a|i|o)"
    id: closet
  - name: "vhod(u|om)|predverj(e|u)"
    id: entrance
  - name: "hodnik(u|ih)"
    id: hallway
  - name: "shramb(a|i|e|ah)"
    id: pantry
  - name: "garderob(a||i|u)"
    id: wardrobe
  - name: "stranišč(e|u|ih)|(v|w)c[ju]"
    id: wc
  - name: "stopnišč(e|u|ih)|stipnic(e|ah|i)"
    id: staircase
  - name: "kuhinj(a|i|e|jah|ski|ska|ske|skih)"
    id: kitchen
  - name: "dnevna soba|dnevni sobi|dnevne sobe"
    id: living_room
  - name: "kopalnic(a|i|o|ah|ama)"
    id: bathroom
  - name: "utility"
    id: utility
entities:
  - name: "nočn(a|e|i) (svetil(ka|ke|a|o)|svjetl(o|a)|rasvjet(a|i|u)|luč(ka|i|ke|ki))"
    id: light.bedroom_lamp
    area: bedroom
    state: "off"

  - name: "luč(i|ke) na terasi"
    id: light.terrace
    area: terrace
    state: "off"

  - name: "luč(i|ke) na balkonu"
    id: light.balcony
    area: balcony
    state: "off"

  - name: "kuhinjs(ko|ka|ki) stikal(o|la|li)|tipk(a|lo|li)"
    id: switch.kitchen
    area: kitchen
    state: "on"

  - name: "stropn(i|a|e|nemu) ventilator(ja|je|ju)"
    id: fan.ceiling
    area: living_room
    state: "on"

  - name: "lesten(ec|ca|ce)"
    id: light.chandalier
    area: living_room
    state: "on"

  - name: "božične luč(ke|i|ki|ko)|"
    id: light.chrismas_ligths
    area: living_room
    state: "on"

  - name: "taln(o|a|e|i) svetilk(a|e|i|o)"
    id: light.floor_lamp
    area: living_room
    state: "on"

  - name: "[stropni] ventilator [na stropu]"
    id: fan.ceiling
    area: living_room
    state: "on"

  - name: "[kuhinjsk(a|o)] (napa|napo)"
    id: fan.kitchen_hood
    area: kitchen
    state: "on"

  - name: "lev(a|o|i|e) zaves(a|i|o|e)"
    id: cover.curtain_left
    area: living_room
    state: "open"
    attributes:
      device_class: curtain

  - name: "dvoriščn(a|i|e) vrat(a|i|e)"
    id: cover.main_gate
    area: "entrance"
    state: "closed"
    attributes:
      device_class: gate

  - name: "garaž(a|na|ne|i|o)"
    id: cover.garage_doors
    area: "garage"
    state: "closed"
    attributes:
      device_class: garage

  - name: "balkonsk(a|e|i) rolet(e|a|i)"
    id: cover.balcony_blinds
    area: "living_room"
    state: "closed"
    attributes:
      device_class: blinds

  - name: "kopalnišk(o|a|i) okn(a|o|i)"
    id: cover.bathroom_window
    area: "bathroom"
    state: "open"
    attributes:
      device_class: window

  - name: "strešn(a|o|i) okn(o|i|a)"
    id: cover.ceiling_window
    area: "kitchen"
    state: "open"
    attributes:
      device_class: window

  #door
  - name: "vhodn vrata"
    id: cover.entrance_door
    area: "entrance"
    state: "closed"
    attributes:
      device_class: door

  - name: "kuhinjska vrata"
    id: cover.kitchen_door
    area: "entrance"
    state: "open"
    attributes:
      device_class: door

  - name: "drsna vrata"
    id: cover.living_room_door
    area: "living_room"
    state: "open"
    attributes:
      device_class: door

  - name: "razvlaževalec|razvlažilnik (zraka)"
    id: "humidifier.dehumidifier"
    area: "living_room"
    state: "off"

  - name: "radiator|radiatorji"
    id: "climate.trv_living_room"
    area: "living_room"
    state: "21"
    attributes:
      unit_of_measurement: "°C"

  - name: "zunanja temperatura|[temperatura] zunaj"
    id: "sensor.outside_temperature"
    state: "17"
    area: "zunaj"
    attributes:
      unit_of_measurement: "°C"

  #locks
  - name: "vhodna vrata"
    id: "lock.front_door"
    area: "entrance"
    state: "locked"

  - name: "vhodna vrata"
    id: "lock.front_door"
    area: "predsoba"
    state: "locked"

  - name: "Zadnja vrata"
    id: "lock.back_door"
    area: "kitchen"
    state: "unlocked"

  - name: "Dvoriščna vrata"
    id: "lock.yard_door"
    state: "locked"

  - name: "Dovozna vrata"
    id: "lock.yard_gate"
    state: "locked"

  - name: "Igranje"
    id: "scene.play_mode"

  - name: "sesaj|posesaj kuhinjo"
    id: "script.vacuum_clean_kitchen"
```



In `light_HassTurnOn.yaml` I have (I went for Croatian way:):


```
language: sl
intents:
  HassTurnOn:
    data:
      - sentences:
          - Vklopi luči v dnevni sobi
        intent:
          name: HassTurnOn
          slots:
            area:
              - dnevni sobi
            domain: light
        response: "Luči so vklopljene"

      - sentences:
          - "Vklopi luč v kuhinji"
        intent:
          name: HassTurnOn
          slots:
            area:
              - kuhinji
            domain: light
        response: "Luč je vklopljena"

      - sentences:
          - Vklopi luči na hodniku
        intent:
          name: HassTurnOn
          slots:
            domain: light
            area:
              - hodniku
        response: "Luči so vklopljene"
```

So, I assume I should check responses...and I referenced from Croatian file HassTurnOn and changed it accordingly:

```
language: sl
responses:
  intents:
    HassTurnOn:
      default: "Vklapljam {{ state.domain }}" #default: Naprava {{ slots.name }} je vklopljena
      default_name: "Vklapljam {{ slots.name }}"
      lights_area: "Luč je vklopljena" #lights_area: Luči v {{ slots.area }} so vklopljene
      fans_area: "Ventilator je vklopljen" #fans_area: Ventilatorji v {{ slots.area }} so vklopljeni
      cover_device_class: "Odpiram {{ slots.device_class }}" #cover_single: "Odpiram {{ slots.name }}" #cover: Senčilo {{ slots.name }} je odprto
      cover_single: "Odpiram {{ slots.name }}" #cover_area: Senčila v {{ slots.area }} so odprta
      lock: "Zakljenjena"
      scene: "Aktivirana"
      script: "Zagnana"
```

comments in file is the old config, as I said I try to head the HR way because it works.

One thing I don't understand in `light_HassTurnOn.yaml` I have this sentence configured:
```
- sentences:
          - "Vklopi luč v kuhinji"
        intent:
          name: HassTurnOn
          slots:
            area:
              - kuhinji
            domain: light
```
Why is the `area:` like `- kuhinji` and not `- kuhinja` ? Is this OK?

file `_common.yaml` : 

```
language: "sl"
responses:
  errors:
    no_intent: "Oprosti, tega nisem razumel"
    no_area: "Območje z imenom {{ area }} ne obstaja"
    no_domain: "V območju {{ area }} ne obstaja {{ domain }}"
    no_device_class: "V območju {{ area }} ne obstaja {{ device_class }}"
    no_entity: "Ni naprave ali entitete z imenom {{ entity }}"
    handle_error: "Med izvajanjem je prišlo do nepričakovane napake"
lists:
  color:
    values:
      - in: "bela"
        out: "white"
      - in: "črna"
        out: "black"
      - in: "rdeča"
        out: "red"
      - in: "oranžna"
        out: "orange"
      - in: "rumena"
        out: "yellow"
      - in: "zelena"
        out: "green"
      - in: "modra"
        out: "blue"
      - in: "vijolična"
        out: "purple"
      - in: "rjava"
        out: "brown"
  brightness:
    range:
      type: "percentage"
      from: 0
      to: 100
  temperature:
    range:
      type: "temperature"
      from: 0
      to: 100
  temperature_unit:
    values:
      - in: "C | stopinj[a|i|e] [Celzija]"
        out: "celsius"
  brightness_level:
    values:
      - in: (max|maximum|highest)
        out: 100
      - in: (minimum|lowest)
        out: 1
  on_off_states:
    values:
      - in: "vklopljen[a|o|i]|vključen[a|o|i]"
        out: "on"
      - in: "izklopljen[a|i]|izključen[a|i|o]"
        out: "off"
  on_off_domains:
    values:
      - in: "luč[i]|svetilo[a]"
        out: light
      - in: "ventilator[ji|ja]|ventilacija[je]|prezračevanje"
        out: fan
      - in: "stikalo[a|i]|gumb[a|i]|tipka[i|e]"
        out: switch
  cover_states:
    values:
      - in: "odprt[a|i|o]|dvignjen[a|i|o]"
        out: "open"
      - in: "zaprt[o|a]|spuščen[a|i|o]"
        out: "closed"
      - in: "odpiram"
        out: "opening"
      - in: "zapiram"
        out: "closing"
  cover_classes:
    values:
      - in: pergol(a|e|o|i)|tend(a|e|o|i)|nadstrešnic(a|o|i|e)
        out: awning
      - in: rolet(a|e|i|o)|senčil(o|a|i)|senčnik[a|i]|rol[o|ji|ja]
        out: blind
      - in: zavesa(a|e|o)|zastor[a|i]
        out: curtain
      - in: vrata
        out: door
      - in: garažna vrata
        out: garage
      - in: vrat(a|i)
        out: gate
      - in: žaluzij(a|e|o|e)
        out: shade
      - in: zapah[i|e]|pokrov
        out: shutter
      - in: okn[a|i]
        out: window
  lock_states:
    values:
      - in: "zaklenjen[a|i|o]"
        out: "locked"
      - in: "odklenjen[a|i|o]"
        out: "unlocked"
expansion_rules:
  name: "{name}"
  area: "[v [prostoru] | na] {area} [sobi]"
  brightness: "{brightness} [procent[a|e|ov] | odstot[e]k[a|e|ov]]"
  temperature: "{temperature}[°| <stopinj>] [{temperature_unit}]"
  stopinj: "[stopinj[a|i|e]]"
  temp: "(stopinj[a|i|e] | temperatur[a|i|e|o])"
  set: "(nastavi | spremeni | prilagodi | segrej | ohladi)"
  close: "(zapri | spusti | zagrni | zatesni | z[a]vij)"
  open: "(odpri | dvigni | odgrni | razkrij | razvij)"
  covers: "([garažna | vhodna | balkonska | zadnja | sprednja | drsna]) vrata | [strešn(o|i|a)] okn(o|i|a) | rolet(o|i|e) | žaluzij(o|i|e) | markiz(a|i|e|o) | tend(a|i|e|o) | [pokrov | pokrivalo] bazena | ograj(a|i|e|o)"
  vklopi: "vključi[te|mo]|vklopi[te|mo]"
  vključi: "vključi[te|mo]|vklopi[te|mo]"
  izklopi: "izključi[te|mo]|ugasni[te|mo]"
  izključi: "izključi[te|mo]|ugasni[te|mo]"
  spremeni: "prilagodi[te|mo]|nastavi[te|mo]|zamenjaj[te|mo]|zmanjšaj[te|mo]|povečaj[te|mo]"
  odpri: "odpri[te|mo]|dvigni[te|mo]"
  zapri: "zapri[te|mo]|spusti[te|mo]"
  katera_je: "katera je|povej [mi]|katerakoli|katero"
  kakšna_je: "kakša je|povej [mi]"
  vse: "[vsi|vsa|vse]"
  lock: "vrata"
skip_words:
  - "prosim"

```

Can't really find the reason besides that I translate the rest :)

Guys, I'm really glad for your help!!!!

**Comment by tetele** [comment]
Don't use sentence syntax in fixtures. The fixtures are basically a simulation of what HA would provide to the intent recognition component and since you don't have names like `teras(a|i|o)` for an area in HA, you shouldn't have them in fixtures either.

These are only used for tests. It's ok to be a little bit more rigid, as it's only a test.

**Comment by andrejs2** [comment]
Thanks @tetele, I corrected to `kuhinja` and for whis I tested it with:
`python3 -m script.intentfest parse --language sl --sentence 'vklopi luč v kuhinji'`
```

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/github2/intents/script/intentfest/__main__.py", line 29, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/github2/intents/script/intentfest/__main__.py", line 24, in main
    return module.run()
           ^^^^^^^^^^^^
  File "/home/github2/intents/script/intentfest/parse.py", line 89, in run
    render_response(response_template, result, matched, unmatched)
  File "/home/github2/intents/shared/__init__.py", line 159, in render_response
    assert response_template, "Empty response template"
AssertionError: Empty response template
```

And if I test it with `'vklopi luč v kuhinja'`

I get:
```
{
  "text": "vklopi luč v kuhinja",
  "match": false
}
```

**Comment by tetele** [comment]
Please read the documentation on how to write intents.

[This is how you include placeholders in your sentences](https://developers.home-assistant.io/docs/voice/intent-recognition/template-sentence-syntax)
[This is how you define a response](https://developers.home-assistant.io/docs/voice/intent-recognition/template-sentence-syntax#responses)

In your case, in `sentences/sl/light_HassTurnOn.yaml`, you should probably have something less hard-coded, like:
```yaml
language: sl
intents:
  HassTurnOn:
    data:
      - sentences:
          - "Vklopi luč v {area}"
        intent:
          name: HassTurnOn
          slots:
          #   area: # <- i've commented these out, but you should remove them, as the {area} is dynamically filled from fixtures
          #     - kuhinji
            domain: light
        response: default # <- notice the key from responses/sl/HassTurnOn.yaml
```

Read up on the [documentation for contributing](https://developers.home-assistant.io/docs/voice/intent-recognition/contributing) and check out the structure defined for English in `sentences/en`, `responses/en` and `tests/en`

**Comment by tetele** [comment]
I just noticed you don't have any light attached in the kitchen in your fixtures, so even with the modifications above, there's nothing to turn on.

A test should sound like this: "Given the stuff defined in `tests/sl/_fixtures.yaml` with fixed names, if I say any of the the exact sentences X1..Xn, I expect the exact response Y and the slots Z1..Zn"

To test that, the recognizer will go through all of the sentences you defined in `sentences/sl`, provide them with the predefined slots `name` and `area`, try to match any one of them given the constraints defined through `requires_context` and `excludes_context`, then see what response key the match offers. After that, it goes to the `responses/sl/WhateverMatchedIntent.yaml` and gets the response text, substitutes the placeholders with actual matched entity info (e.g. `name`, `area`, `slots` etc.) and returns the response.

If the returned response matches your expected response, the test will pass.

**Comment by andrejs2** [comment]
Aha, thank for the logic behind it @tetele ! Tried to go through the large amount of docs since I'm quite a noob, sorry...
I'll get back to you and report :)
Have a nice day!

**Comment by spuljko** [comment]
Define "luč(i|ke) na terasi" as "luč[i|ke] na terasi" so it will match luč, luči and lučke.
Try to name your entities differently, maybe it will help you figuring stuff out - instead of "luč na terasi" name it for example "solarn(e|o) luč[i|ke". That way you will know if you are calling area sentences or entity sentence (vkopi luči na terasi -> area - that will turn all lights, vklopi solarne lučke -> entity - that will only turn on that named entity. you can also write "vklopi solerne lučke na terasi")

**Comment by andrejs2** [comment]
OK, thank you @tetele @spuljko ! I'm having some progress. My first sucessful test 👍 : 
`python3 -m script.intentfest parse --language sl --sentence 'vklopi luč na terasi'`

and output:
```
{
  "text": "vklopi luč na terasi",
  "match": true,
  "intent": "HassTurnOn",
  "slots": {
    "name": "luč na terasi"
  },
  "context": {
    "domain": "light"
  },
  "response_key": "default_name",
  "response": "Vklapljam luč na terasi"
```

**Comment by andrejs2** [comment]
@tetele @spuljko thank you again so much for help and guidance with my first PR and commit :). 

For me as unexperienced in github wokflow and in coding the learing curve is very steep :) but I'll try to do my best not to bother you too much. 
Thanks for relevant docs!

**Comment by tetele** [comment]
We all started someplace.

Don't forget to add tests to your ever-growing PR. When I see tests added, I'll approve the CI run on your PR.

**Comment by tetele** [comment]
From [here](https://github.com/home-assistant/intents/issues/1568#issuecomment-1772253325)
> Read up on the [documentation for contributing](https://developers.home-assistant.io/docs/voice/intent-recognition/contributing) and check out the structure defined for English in `sentences/en`, `responses/en` and `tests/en`

**Comment by andrejs2** [comment]
Reading [here](https://developers.home-assistant.io/docs/voice/intent-recognition/contributing/)
but can't find out of I should c/p files from `sentences` dir to `tests` dir, the [link](https://developers.home-assistant.io/docs/voice/intent-recognition/contributing/test-syntax) is broken.

**Comment by andrejs2** [comment]
@tetele or @spuljko I kindly ask for help...

I read the [docs](https://developers.home-assistant.io/docs/voice/intent-recognition/template-sentence-syntax/#responses) and try to figure out the responses. In [[en] responses](https://developers.home-assistant.io/docs/voice/intent-recognition/template-sentence-syntax/#responses) file is following:
```
language: en
responses:
  intents:
    HassLightSet:
      brightness: '{{ slots.name }} brightness set to {{ slots.brightness }}'
```

But in actual [responses file from repo](https://github.com/home-assistant/intents/blob/main/responses/en/HassLightSet.yaml) is following:
```
language: en
responses:
  intents:
    HassLightSet:
      brightness: "Brightness set"
      color: "Color set"
```
So in actual response file there is no template used...but is there any other relevant difference between there two files?
I try to understand what't wrong with my sentences and I try to understand this with "reverese" engineering :).

Second question:
`WARN] responses/sl/HassTurnOn.yaml: unused response default` Has  `default`  also be provided? Is there any example?

Big thanks to any suggestion and hint :)!!!

**Comment by spuljko** [comment]
You can use templates in response (check other files), but I would recommend to keep it as simple as you can, or you will find you in grammar rules hell.
Warning is that you have response you are not using in sny sentence, you can delete that response if you don't need it.

**Comment by andrejs2** [comment]
Thanks @spuljko . Getting some progress after 2 days of beeing stuck with light_HassLightSet sentence. Started test, sentence and response file from only 1 sentence...and finally test passed!!!

No clue, how the light_HassLightOff did pass it, with very similar structure, but I'm very happy I did it. 

I got now from here with small steps :)) Thank you again for support! It means a lot! 🥇

**Comment by tetele** [comment]
> In [[en] responses](https://developers.home-assistant.io/docs/voice/intent-recognition/template-sentence-syntax/#responses) file is following:

That's just an example in the docs, it's not the EN responses file. Anyway, glad you figured it out
