### ISSUE TITLE
[fr] light sentences

### ISSUE THREAD

**Issue by Aohzan** [home-assistant/intents#1595]
Hello,

Two sentences that doesn't seem to be supported, is it normal ?

1) I can't set level if brightness of a light with the sentence `Allume la lumière du salon à 10%`

2) When I want to turn off all the lights of the house, I want to say `Éteint toutes les lumières`, but I have this error `homeassistant.helpers.intent.IntentHandleError: No area named all`

Thank you
```[tasklist]
### Tasks
```

**Comment by flexy2dd** [comment]
Hello,
 Indeed, it should work I'll have a look
