### ISSUE TITLE
Media Player Intents

### ISSUE THREAD

**Issue by RoepLuke** [home-assistant/intents#1623]
I want to control a media player entity with Assist (play, pause, forward, backward, lower volume, higher volume, etc). 

When testing I was unable to control a media_player entity that was exposed to Assist.
I also did not find any sentence files for the media_player domain.

I'd be willing to contribute the sentences in english and german. However I assume there are other prerequisites that need to be fullfilled to achieve this.

**Comment by tetele** [comment]
There are other requisites for it to function, not necessarily **pre**requisites.

Feel free to go for it, expect multiple rounds of reviews :D And thanks for wanting to contribute!

**Comment by skynetua** [comment]
Intents need to be added at first.

https://developers.home-assistant.io/docs/voice/intents/

**Comment by sorgfresser** [comment]
If we're talking about adding these intents (for example to the jellyfin component or whatever media_player you were referring to), what intents would you want in particular? You named a few, but ended with etc. What else did you have in mind?

**Comment by skynetua** [comment]
Most of [mp control services](https://www.home-assistant.io/integrations/media_player/#media-control-services)

**Comment by sorgfresser** [comment]
So I wanted to get into home-assistant and started some small pr focusing on volume up and volume down intents at the core repository. Other than the intents in core, is there any other requisite besides the intents here @tetele ?

**Comment by Ay1tsMe** [comment]
I think media player intents should have room specific features similar to the light intents. For example, I should be able to say: "Pause music"  or "Play music"
and it will pause/play the music in the same area as the voice satellite if there is a media player configured.

**Comment by tetele** [comment]
> Other than the intents in core, is there any requisite besides the intents here @tetele ?

Nope, that's about it @sorgfresser. Here you have to create sentences, responses and tests. We could do that before the `core` intents and mark the intent as [unsupported](https://github.com/home-assistant/intents/blob/8ba1a10bcd21ebf2baee7efbb3bb87b1794fd0e3/intents.yaml#L118), but I think a coordinated effort would do better.

**Comment by dontinelli** [comment]
With #1967 I think this issue can be closed.

**Comment by sorgfresser** [comment]
Right now, there is no "play {songname}" intent. Would this be a nice feature to have? I image it might be a bit tedious because the ASR isn't great and thus songnames might be misunderstood.
