### ISSUE TITLE
Responses for custom intents doesn't work.

### ISSUE THREAD

**Issue by UchihaYuki** [home-assistant/intents#1664]
```
#/config/custom_sentences/en/example.yaml
language: "en"
intents:
  ExampleIntent:
    data:
      - sentences:
          - "do you love me"
        response: "default"

#/config/custom_sentences/en/example_responses.yaml
language: "en"
responses:
  intents:
    ExampleIntent:
      default: "of course baby"
```
![image](https://github.com/home-assistant/intents/assets/38900426/55d759fb-a36c-418d-858b-c5bd5782b38c)
More details:
https://community.home-assistant.io/t/how-to-set-speech-language-of-intent-script/643384/2

**Comment by tetele** [comment]
The response is missing from the custom intent. I've detailed how to set a custom response [on the community forums](https://community.home-assistant.io/t/how-to-set-speech-language-of-intent-script/643384/7).
