### ISSUE TITLE
[UK] Non cyrillic symbol in the command

### ISSUE THREAD

**Issue by b-des** [home-assistant/intents#1823]
Hi!
The wrong symbol 'C' was found in the one of climate commands. Seems it was substituted with English 'C'(67)  instead of Ukrainian 'С'(208 161). Here is the link to command:
https://github.com/home-assistant/intents/blob/2381a442a96ace1ac98a55fdea7634a20558d0d9/sentences/uk/climate_HassClimateGetTemperature.yaml#L8C25-L8C25

There is wrong first letter in '`Cкільки`'

**Comment by skynetua** [comment]
Nice catch, thanks

*Never use copy/paste for tests, Never)
