### ISSUE TITLE
[all language] [request] Option to set 'zone_states' in _common.yaml

### ISSUE THREAD

**Issue by v1k70rk4** [home-assistant/intents#1880]
Hello,
I have a question regarding whether it could be simple to include a 'zone_states' section in the _common.yaml file. It would be sufficient to have just the 'home' and 'not_home' statuses, as I believe these are special cases in many languages. I am aware of the issue that this is not yet perfect (ticket #1768), but even afterwards, it poses a problem in Hungarian.

In Hungarian, the word for 'home' is special because it's only 'otthon' (home) when someone is not there :) When the person in question is at home, we call it 'itthon' (home). Also, the 'not_home' (Away) status is similar in that we don't use the question 'who is away?' but rather 'who is not at home?'

With this, we wouldn't even need to address the part of Issue #1768 related to zones, as the following part, which I have already included in the Hungarian translation, could be used in the answers:
```
          {% if state.state == 'home' %}
            Nem, otthon van                    #home
          {% elif state.state == 'away' %}
            Nem, nincs otthon                  #away
          {% else %}
            Nem, itt van: {{ state.state }}    #other
          {% endif %}
```
In the responses, 'otthon' (home) is appropriate because it is completely understandable, but personally, out of habit, I ask if I am 'itthon' (at home) when I am home.

And thank you to everyone for the work put into this! While translating, I realized that you tried to extract everything possible from it! Practically, I was able to apply the templates to the Hungarian language almost 100%.

**Comment by tetele** [comment]
First of all, the `person_HassGetState` does not properly work in any language. See [this discussion](https://github.com/home-assistant/intents/discussions/1768). I wouldn't invest a lot of time in translating something that won't work regardless of how well you translate every form of "home".

Second, for sentences referencing multiple entities (e.g. `is {person} at {zone}`), we will need a major overhaul of how things work.

My proposal, which @synesthesiam liked, but which I haven't had time to work on, was to have a special type of list that is an entity filter. So you have a predefined list of entities (what's now in `name`), and then other lists (global or local) which apply one or more filters to the big list (based on `domain`, `device_class` etc.) which will make sense in the context of a sentence. For example

```yaml
language: "en"
intents:
  HassGetState:
    data:
      - sentences:
          "is {person} at {zone}"
        response: one_yesno
        lists:
          person:
            entity_filter:
              domain: person
          zone:
            entity_filter:
              domain: zone
```

At the moment you can only reference a single entity in sentences (via `{name}`) and you'd have to filter the entities that should match the query using `requires_context` and `excludes_context`. My proposal would eliminate the need of `requires_context` and `excludes_context` for domains and device classes and would allow the use of multiple entities in the same sentence.

**Comment by v1k70rk4** [comment]
@tetele I misunderstood things a bit. But now I get it.
Thank you.
