### ISSUE TITLE
[SK] Bad response for HassClimateGetTemperature

### ISSUE THREAD

**Issue by brano6** [home-assistant/intents#1911]
There is problem in "official version" with response HassClimateGetTemperature and for now it s not working correctly. 

I add my code which is working in my HA.
[HassClimateGetTemperature.txt](https://github.com/home-assistant/intents/files/14129610/HassClimateGetTemperature.txt)

**Comment by v1k70rk4** [comment]
Details in the https://github.com/home-assistant/intents/discussions/1875  discussion.

**Comment by LubosKadasi** [comment]
Thank you both for your collaboration
