### ISSUE TITLE
Implement 'stop cover' intent and sentences (during opening or closing cover)

### ISSUE THREAD

**Issue by andrejs2** [home-assistant/intents#2047]
Proposal for implementing `coverStop` intent and corresponding sentences.

When the sentence is called: '`open the blinds`'  or '`close the blinds`' the HA starts opening the `blinds`.

Adding sentences and intent for `cover `to `stop `when `opening `or `closing `(e.g. `coverHassStop`) will `stop opening` / `closing` cover.

This intent can be useful with `cover `which takes some time to `open`/`close `and will allow to` stop cover` at desired position (e.g. sun, shade position,...) in no relation to `HassSetPosition` intent (when desired `position` in % could be a bare guessing for a user).

Thanks!

**Comment by v1k70rk4** [comment]
Well, this might not be the right place to address this issue since it's not a bug. It's worth bringing it up here, perhaps: https://community.home-assistant.io/tag/voice-assistants

By the way, it seems useful, but I don't know which STT you're using. By the time I'd say "ok nabu, stop the living room blinds" and it even recognizes it, all of them would have already gone down :)

**Comment by andrejs2** [comment]
@v1k70rk4 Thanks, I'll be addressing the proposal there. The `stop the living room blinds` or just option to `stop cover` could be (more) useful when having a `continuous conversation` which is starting to be implemented on satellites. Anyways, my blinds take around 55s to fully open/close, the wake-word plus sentence is less than that (maybe 10s).

**Comment by tetele** [comment]
> By the time I'd say "ok nabu, stop the living room blinds" and it even recognizes it, all of them would have already gone down

The current processing speed (which also depends a lot on hardware and network connectivity, so results vary between users) should not be detrimental to future improvements. I think that this intent is a welcome addition.

**Comment by andrejs2** [comment]
Closing this issue because is't not an issue. Moving to discussions - https://github.com/home-assistant/architecture/discussions/1053
