### ISSUE TITLE
Support for Russian (Русский) language

### ISSUE THREAD

**Issue by JugglerLKR** [home-assistant/intents#205]
I would like to try. I see @HepoH3 is already working on it. Probably close this one.

**Comment by HepoH3** [comment]
As far as I understend, there could be multiple leaders (see [languages.yaml](https://github.com/home-assistant/intents/blob/main/languages.yaml). I don't mind if you join me, not sure how it works, think we need someone like @balloob, to make this clear.
For now you can checkout what already done, try to change things in the sandbox to see result (maybe broke some test to see how tests works). Moreover you can checkout current [problem](https://github.com/home-assistant/intents/pull/164) with slovanic languages with word cases (с падежами), maybe you'll have an idea how to solve the problem.
If you'll have any problems with tests, feel free to contact me through telegram: (hepoh).

**Comment by balloob** [comment]
Language leaders are responsible for verifying contributions in a certain language. You don't have to be a language leader to contribute though, anyone can open a PR.

**Comment by balloob** [comment]
Going to close this issue, as support for Russian is there.
