### ISSUE TITLE
[FR] % written "pour cent" not taken into account in brightness. 

### ISSUE THREAD

**Issue by mdelpire** [home-assistant/intents#2064]
Hi,

I tested assist in French to turn my lights on and it works great. Then I tried to use it to set the brightness of some dimmable lights. The issue is that my speech to text sometimes translate % as "pourcent" (correct orthography) and sometimes as "pour cent" (incorrect orthography but pronounced exactly the same. When the second is picked, I got the message that HA doesn't know the room "50 pour cent" for instance. Is there a way to make it understand as a synonym?

Thanks

**Comment by slegars56** [comment]
Hi @mdelpire, I had the same when testing the cover position with local STT. Push request done.

**Comment by piitaya** [comment]
Fixed with https://github.com/home-assistant/intents/pull/2088
