### ISSUE TITLE
[FR] Issue turning off the lights

### ISSUE THREAD

**Issue by crazyactions** [home-assistant/intents#2112]
Hi,

I'm currently testing the intents for my home assistant, and it's performing well when it comes to turning things on, with "allume" being easily recognized. However, I'm encountering difficulties when trying to turn things off. For instance, when I say "éteins," it seems to interpret it as "Etais," "été," "Et t'as," or "état." How can we incorporate these variations into the standard intent to improve its service ?

Thank you

**Comment by jlpouffier** [comment]
ON it.

**Comment by piitaya** [comment]
Fixed with https://github.com/home-assistant/intents/pull/2120
