### ISSUE TITLE
Dutch curtain open and close intent dont work 

### ISSUE THREAD

**Issue by zarya** [home-assistant/intents#2128]
### The problem

The "Open de gordijnen in de woonkamer" (Open the curtains in the livingroom) intent does not seem to find any curtains while the "Hoeveel gordijnen zijn er open in de woonkamer" (how many curtains are open in the livingroom) Does

### What version of Home Assistant Core has the issue?

2024.4.1

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[intent_results.json](https://github.com/home-assistant/core/files/14901639/intent_results.json)

**Comment by zarya** [comment]
I dont have a entity named gordijnen also asking the English intent to turn on gordijnen does not result in any entities being turned on
```json
    {
      "sentence": "turn on gordijnen",
      "language": "en",
      "result": {
        "intent": {
          "name": "HassTurnOn"
        },
        "slots": {},
        "details": {},
        "targets": {},
        "match": false,
        "sentence_template": "<turn> on (<area> <name>|<name> [in <area>])",
        "unmatched_slots": {
          "name": "gordijnen"
        },
        "source": "builtin"
      }
    },

**Comment by TheFes** [comment]
This should work now after the next update of intents in HA.
So that will be in 2024.6.0
