### ISSUE TITLE
[es] can't turn on lights as usual

### ISSUE THREAD

**Issue by luca-angemi** [home-assistant/intents#2203]
![image](https://github.com/home-assistant/intents/assets/9977955/2d7cf2a7-e454-4a58-ab87-83c811ffe9e7)

why script???

![image](https://github.com/home-assistant/intents/assets/9977955/23aaff4e-27a4-4d7b-a502-e7f8d37810fb)

**Comment by DAVIZINH0** [comment]
Buenas.
Quizás no sea lo mismo que comenta el compañero pero como la veo abierta y se parece lo consulto.
Si sobra disculpadme.

He probado a poner a una bombilla el alias "lamparita" y está en la habitación "salón".
Pues sl le digo a assist, "enciende la lamparita del salón" no lo entiende.
Mirando en las sentencias me da la sensación que tendría que decir, "enciende la luz lamparita del salón" para que funcionará.
Es posible?

**Comment by luca-angemi** [comment]
Es exactamente lo mismo, en 2024.5 no era necesaria la palabra luz

**Comment by DAVIZINH0** [comment]
> Es exactamente lo mismo, en 2024.5 no era necesaria la palabra luz

Ah vale. Te refieres que en la versión anterior no era necesaria la palabra luz y ahora si.
OK ok
Que mala suerte la mía que justo lo estoy probando ahora y no antes. Jeje

Gracias por la información compañero

**Comment by davefx** [comment]
Should be fixed with #2245
