### ISSUE TITLE
[de] add article to area

### ISSUE THREAD

**Issue by ChristophCaina** [home-assistant/intents#2216]
```
      - sentences:
          - "Wie [hoch|niedrig] ist <artikel> Temperatur [<area>]"
          - "Wie [hoch|niedrig] ist <area> <artikel> Temperatur"
          - "Wie [hoch|niedrig] ist <artikel> Temperatur [<von_dem>] <name>"
          - "Wie [hoch|niedrig] ist <artikel> Temperatur des <name>[s]"
          - "Wie [hoch|niedrig] ist <artikel> Temperatur <von_dem> Thermostat <area>"
          - "Wie [hoch|niedrig] ist <artikel> Temperatur des Thermostat[s] <area>"
          - "Wie (warm|kalt) ist es <area>"
          - "<wieviel> Grad [hat|sind] es <area>"
 ```
 
 Add:
 - `<wieviel> Grad [hat|sind] es **im / in der** <area>`
 
 Also, it would be great, if Assist could return something like: "it is 21.2 degree" - and not: "It is 21.2"

**Comment by andreasbrett** [comment]
> Add:
> 
> * `<wieviel> Grad [hat|sind] es **im / in der** <area>`

Articles are already provided in the expansion rules for area. Note that `<area>` reference an expansion rule while `{area}` references a sole area. See https://github.com/home-assistant/intents/blob/97488d9aceef0b2b57f262f86a9afa9ff9a40271/sentences/de/_common.yaml#L263

> Also, it would be great, if Assist could return something like: "it is 21.2 degree" - and not: "It is 21.2"

Agreed, sounds much more natural that way. This is also implemented for EN, so I'm not sure why this did not make it into DE. Added in PR https://github.com/home-assistant/intents/pull/2267.
