### ISSUE TITLE
Danish language leader

### ISSUE THREAD

**Issue by fadamsen** [home-assistant/intents#230]
Hi! I would like to apply for the position as Danish language leader. I’m a native Danish speaker and have experience with internationalisation and localisation of software.

Looking forward to contributing!

**Comment by fadamsen** [comment]
Hi @rhl2401! I think all interested Danish speakers should cooperate as well!

I’ve already started work on sentences. There have also been some interest expressed on Discord, but no contributions so far, but now that the holidays are over, that might change, of course.

**Comment by fadamsen** [comment]
I expect to finish work on all sentences this week, by the way. That’ll give us time to discuss any changes we might want to make before the first release.

**Comment by synesthesiam** [comment]
Discussion moved here: https://github.com/home-assistant/intents/discussions/345
