### ISSUE TITLE
Add devenv support

### ISSUE THREAD

**Issue by nagyv** [home-assistant/intents#2341]
Are the maintainers open to moving the `./scripts/setup` to [devenv](https://devenv.sh/getting-started/)?

While it's nice that the setup script creates a dedicated virtualenv, devenvs are a bit more powerful, and at the same time very easy to use for the "end user" / contributor.

**Comment by frenck** [comment]
There is no need to create an issue for making a PR.

Let's discuss in the PR instead.

../Frenck
