### ISSUE TITLE
[BUG] “off” triggers intent “name: HassTurnOff” which turns off all lights

### ISSUE THREAD

**Issue by tetele** [home-assistant/intents#2379]
### Discussed in https://github.com/home-assistant/intents/discussions/2360

<div type='discussions-op-text'>

<sup>Originally posted by **bcutter** July 31, 2024</sup>
Please see https://community.home-assistant.io/t/off-triggers-intent-name-hassturnoff-which-turns-off-all-lights/752442 for details.

Last post is https://community.home-assistant.io/t/off-triggers-intent-name-hassturnoff-which-turns-off-all-lights/752442/10.</div>

**Comment by mib1185** [comment]
maybe it has been fixed by #1813 , but I did not checked the issue at all, since it get noticed about it to late, after it already has been "solved"
