### ISSUE TITLE
[SL] Fix temperature values for TTS

### ISSUE THREAD

**Issue by thehijacker** [home-assistant/intents#2380]
Same as for Romanian language, the float temperature values must be with comma and not dot, so the Slovenian TTS (Nabu Casa cloud) will correctly read them.

Here was the fix for Romanian language which had same problem: https://github.com/home-assistant/intents/pull/1706

Can this be done also for Slovenian language please?

**Comment by andrejs2** [comment]
@tetele and @thehijacker thanks for notice and issue.

Fixed in https://github.com/home-assistant/intents/pull/2381

**Comment by thehijacker** [comment]
Thank you! Will test once available in next update.

**Comment by andrejs2** [comment]
Now [fixed ](https://github.com/home-assistant/intents/pull/2383)also for sensor and temperature values. This should implement values with decimal comma. Make sure you test sensor values too :)
