### ISSUE TITLE
Swedish Language Leader

### ISSUE THREAD

**Issue by synesthesiam** [home-assistant/intents#259]
@lellky are you interested in being the Swedish language leader? Another person from Discord has volunteered; I'll point them to this issue.

**Comment by edgein666** [comment]
Hi, the person from Discord here.. 🙂 let me know if I can help. BR Björn

**Comment by larsdunemark** [comment]
I can also help out with this if there is need for multiple workers or a work group.

**Comment by lellky** [comment]
Good morning!

I am interested, and it would be an honor, but I have to younglings here at home and I don't know if I have the time to fully commit to be the leader. I will gladly help with reviews and have discussions though.

Also, there is another user _thedailyuncle_ on discord: https://discordapp.com/channels/330944238910963714/1054846248374505572/1056591259944370186
