### ISSUE TITLE
Serbian language leader 

### ISSUE THREAD

**Issue by maretodoric** [home-assistant/intents#266]
Hello everyone.

I'm Marko Todorić and I would like to become a Serbian language leader . I am a native speaker, currently working as a DevOps engineer and beginner Python developer.
I have free time to contribute to this project and would very much like to be involved. Consider myself to r a good fit as I'm very familiar with home assistant as I've been using it fore little over two years now.

**Comment by synesthesiam** [comment]
Thanks @maretodoric! Let's continue the discussion here: https://github.com/home-assistant/intents/discussions/400
