### ISSUE TITLE
[de] - add sentence to cover: "Fahre xyz hoch" / "Fahre xyz herunter"

### ISSUE THREAD

**Issue by ChristophCaina** [home-assistant/intents#2719]
the [cover_HassTurnOff.yaml](https://github.com/home-assistant/intents/blob/main/sentences/de/cover_HassTurnOff.yaml) should include the sentence: 
`Fahre <device> (im <area>) herunter`

variation:
`Fahre <device> (im <area>) runter`

the [cover_HassTurnOn.yaml](https://github.com/home-assistant/intents/blob/main/sentences/de/cover_HassTurnOn.yaml) should include the sentence:
`Fahre <device> (im <area>) hoch`

variation:
`Fahre <device> (im <area>) rauf`

**Comment by andreasbrett** [comment]
coming in next release (see linked PR)
