### ISSUE TITLE
[de] - add sentences to "lock"

### ISSUE THREAD

**Issue by ChristophCaina** [home-assistant/intents#2720]
The lock entities should include sentences like:

close:
- `verriegle...`
- `schließe...`

open:
- `entsperre...`
- `öffne...`
- `entriegle...`

**Comment by andreasbrett** [comment]
All of these already exist.

https://github.com/home-assistant/intents/blob/main/sentences/de/lock_HassTurnOff.yaml
https://github.com/home-assistant/intents/blob/main/sentences/de/lock_HassTurnOn.yaml

https://github.com/home-assistant/intents/blob/af6967cdb86132d8f65b34d0b08bca503f04bdb0/sentences/de/_common.yaml#L576

https://github.com/home-assistant/intents/blob/af6967cdb86132d8f65b34d0b08bca503f04bdb0/sentences/de/_common.yaml#L577

https://github.com/home-assistant/intents/blob/af6967cdb86132d8f65b34d0b08bca503f04bdb0/sentences/de/_common.yaml#L575
