### ISSUE TITLE
[DE] Sentence works in tests but fails on live HA

### ISSUE THREAD

**Issue by netmikey** [home-assistant/intents#2770]
I'm trying to open the covers in a given area by saying: "Fahre im Wohnzimmer die Rolläden rauf."

I cloned this repository and added this sentence to `/tests/de/cover_HassTurnOn.yaml` then tested it using `pytest tests --language de -k cover_HassTurnOn` as described in the README. The test went through successfully.

However, when I enter this same sentence into the assist debugging on my HA instance, I get the response "Kein Bereich mit dem Namen Rolläden rauf vorhanden" (debug json attached). This looks like it doesn't parse the sentence correctly as it thinks "Rolläden rauf" is an area though that should be "Wohnzimmer" in this sentence.

[conversation.json](https://github.com/user-attachments/files/18218865/conversation.json)

**Comment by andreasbrett** [comment]
Which version of Home Assistant are you on? This particular sentence is rather new and is only available with HA 2024.12.2+

**Comment by netmikey** [comment]
Oh no, I was indeed still on 2024.12.0, what was the chance I'd hit exactly that phrase in exactly that timeframe... 🙈
Anyways I checked and it works with 2024.12.5. Sorry for the noise.
