### ISSUE TITLE
Malay Language Leader

### ISSUE THREAD

**Issue by jimmy93** [home-assistant/intents#299]
Hi, im ready to contribute for Malay language.

**Comment by anas-ivs** [comment]
ready to contribute too with @jimmy93 as leader

**Comment by zubir2k** [comment]
I'm ready to contribute for Malay language

**Comment by wnas86** [comment]
ready to contribute too with @jimmy93 as leader

**Comment by synesthesiam** [comment]
Discussion continued here: https://github.com/home-assistant/intents/discussions/385
