### ISSUE TITLE
[EL] Greek Language Leader

### ISSUE THREAD

**Issue by dsimop** [home-assistant/intents#310]
I would like to apply for the Greek Language Leader. 
Software engineer / HA User for at least 3 years / Experienced with localisation projects (like the Greek HA Translations in Lokalise)
Already committed the first PR for initial EL Support.

**Comment by synesthesiam** [comment]
Thanks @dsimop! Please coordinate with @gekoul here: https://github.com/home-assistant/intents/discussions/351
