### ISSUE TITLE
What gender should we pick when writting sentences?

### ISSUE THREAD

**Issue by Misiu** [home-assistant/intents#33]
I'm trying to add a new language (Polish) and after running the script I started filling in all the new files.
I noticed that for example, we have this sentence (_common > responses > errors > no_intent):

> Sorry, I couldn't understand that

which can be translated in 2 ways in Polish:

> Nie mogłem tego zrozumieć

or

> Nie mogłam tego zrozumieć

The first one is a male version and the second is a female version.
Even Google Translate suggests two versions:
![image](https://user-images.githubusercontent.com/1741838/208646678-40e7177b-cddd-4d7a-910b-2fca8dcf2daa.png)

Any plans to support this scenario? I'm sure that not only Polish has this rule.
Verbs with past or future complex times have both forms (ref: https://polski.info/pl/grammar/verbs#verbs7), so ideally we should have a way to declare two responses (if we plan to add voices in both genders) or we should specify that if a sentence has multiple forms we should pick one (which?). It will be hard or sometimes impossible to write sentences that are impersonal (non-gender specific)

**Comment by synesthesiam** [comment]
We can add some more options to specify things like the gender of the response template. I don't know enough about Polish to understand how you select which response to speak. Does it depend on the voice of the speaker (text to speech system) or on who is being spoken to (user)?

**Comment by tomatow** [comment]
It depends on both. Voice implicates gender of assistant and person who is spoken to may be also addressed differently. However in many cases, if being smart, it's possible to use neutral form.

**Comment by synesthesiam** [comment]
Thanks! I guess if possible, we'll ask contributors to use the neutral form. And we'll work to add support for hints in the future to the responses, so the correct one can be selected.

**Comment by rrakso** [comment]
Hey @Misiu I'm also writing Polish sentences. Should I still do it? Or do you need my help?

**Comment by Misiu** [comment]
@synesthesiam I think we can write in neutral language (I think that Google Assistant is doing this).
@rrakso I just created the initial files and started to fill the sentences, but I think I won't find time till next week, so if you have something fill free to create PR and mention me in the description. I'll try to do a quick review.

**Comment by ferinelo** [comment]
Maybe simplified neutral form can be used here, like: "Nie rozumiem" instead of tricky "Nie mogłem/am tego zrozumieć"?
Also, sometimes passive form would fit as well, e.g. "Światło nie może być włączone" instead of a form including gender in it: "Nie mogłem/am włączyć światła".

**Comment by Misiu** [comment]
I'm closing this issue because the neutral form is the preferred version.
