### ISSUE TITLE
German Language Leader

### ISSUE THREAD

**Issue by andreasbrett** [home-assistant/intents#349]
Happy to contribute and assist on the german language. Have been using HA for 2 years now and once Snips got sold, I switched my voice assistant setup to Rhasspy. So also some experience with Rhasspy itself.

**Comment by synesthesiam** [comment]
Thanks @andreasbrett! Also glad to hear you have Rhasspy experience :)
German language leader discussion is here: https://github.com/home-assistant/intents/discussions/347
