### ISSUE TITLE
Italian language leader

### ISSUE THREAD

**Issue by jjantoine** [home-assistant/intents#369]
Hi,

I'm Antonio and I'm an Italian Mechatronic Engineer and I love home assistant. I use it for everything since 4 years in two different homes. It would be really amazing to contribute in the community.

Thank you,

Antonio

**Comment by synesthesiam** [comment]
Thanks @jjantoine. Current Italian language leaders are @auanasgheps and @xraver. Please coordinate with them here: https://github.com/home-assistant/intents/discussions/370
