### ISSUE TITLE
Setup scripts failing in Windows 10 - general question about support of Windows OS for development purposes.

### ISSUE THREAD

**Issue by Uriziel01** [home-assistant/intents#403]
Currently the `./script/setup` script does not work properly on Windows10 OS, it almost does work but requires few minor tweaks.

As more and more people are comming to the repository should we maybe go through all the scripts and adjust them for Windows to make life easier for all the contributors and allow for development on all operating systems?

**Comment by balloob** [comment]
Our preferred development approach for people is to use CodeSpaces. You can create a free CodeSpace by going to the repo, hit green button -> code spaces.

**Comment by fadamsen** [comment]
You can also use Windows Subsystem for Linux, that works quite well for me.

**Comment by Uriziel01** [comment]
As @balloob stated the preffered approach is to use CodeSpaces, it works well.
You do not even need WSL (although tested it with WSL Debian 11 and it's all fine there) , it works on plain Windows if you adjust the scripts, but as it is I reckon it is not really worth it to go through everything and fix it for just this one specific case. 

Closing the issue for now. Thanks for the discussion guys 😃
