### ISSUE TITLE
Trigger on either name or device class?

### ISSUE THREAD

**Issue by Robin-St** [home-assistant/intents#493]
I encountered the situation below while editing swedish (translated to ease discussion). 
How to handle the possibility to have a cover that shares the name of a device class, as duplicated test sentences are not allowed? Shall it be assumed that the cover.garage_door always have the device_class set and just remove the test sentence from the test that looks for the device name?  

tests:
  - sentences:
      - "close garage door"
    intent:
      name: HassCloseCover
      slots:
        name: cover.garage_door

  - sentences:
      - "close garage door"
    intent:
      name: "HassCloseCover"
      slots:
        device_class: "garage_door"

**Comment by balloob** [comment]
Make sure your fixtures do not have generic names like "garage door" to avoid having duplicate test sentences.

**Comment by balloob** [comment]
Added it to the documentation: https://voice.home-assistant.io/docs/contributing/intent-sentences#fixtures
