### ISSUE TITLE
Adding Lojban

### ISSUE THREAD

**Issue by ShadowJonathan** [home-assistant/intents#58]
While this is partially a joking suggestion, I do think adding lojban as a language, could be interesting from a parsing/intent suggestion perspective, as the last time I looked at this conlang, it was built extremely logically.

(Note: I'm not at all proficient with the language, I'm putting an issue here out of interest, but also intrigue, due to the above logical/structural properties the language has)

I guess, however, that this also immediately is about the question; will HA consider/support conlangs, and under which conditions, or with what kind of community support.

**Comment by synesthesiam** [comment]
I think this would be cool personally, but it would have to be something completely community supported. One issue is that Home Assistant doesn't have Lojban as a language you can select.

I would say if a constructed language reaches a level that it can be added to HA's list of languages, we should include it here.
