### ISSUE TITLE
`skip_words` are not parsed

### ISSUE THREAD

**Issue by alessandroias** [home-assistant/intents#609]
Im trying to use `HassILGrammar` to define `skip_words` in the italian language's `_common.yaml` file (#607).
I would like to add this line:

```yaml
skip_words:
  [...]
  - "puoi [dirmi]"
```
CI breaks.

While Adding :
```yaml
skip_words:
  [...]
  - "puoi"
  - "puoi dirmi"
```
CI does not break.

Is not parsing `skip_words` the desired behaviour?

**Comment by synesthesiam** [comment]
Correct. Skip words should not contain template syntax. They have their whitespace normalized and are `casefold`-ed, but are otherwise interpreted literally.
