### ISSUE TITLE
Italian sentences that should be supported

### ISSUE THREAD

**Issue by federicoodorizzi** [home-assistant/intents#62]
If you don't feel comfortable contributing to the YAML in this repository, you can post your **Italian** (it) sentences that match [our supported intents](https://github.com/home-assistant/intents/blob/main/intents.yaml) below.

**Comment by xraver** [comment]
Hi! I want to help with italian language

**Comment by echopage** [comment]
Hi, if possible, I would like to contribute to the Italian language

**Comment by xraver** [comment]
Hi @echopage 
refers to [[IT] Italian Support #157](https://github.com/home-assistant/intents/pull/157)
