### ISSUE TITLE
Garage door sentense cause exception for 'en'

### ISSUE THREAD

**Issue by skynetua** [home-assistant/intents#708]
https://github.com/home-assistant/intents/blob/b7953057b802908865c6c8283fd4b743b8430b8e/sentences/en/homeassistant_HassTurnOn.yaml#L17

Cover response require slot name
     ` cover: "Opened {{ slots.name }}"`
which is absent with such sentense.

It couses exception:
```
  File "<template>", line 1, in top-level template code
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'name' 
```

**Comment by schizza** [comment]
The same is with setting temperature or getting temperature.

`python3 -m script.intentfest parse --language cs --sentence 'jaká je teplota'    - menas: what is the temperature?`

Just produces error
```
 File "/home/vscode/.local/lib/python3.10/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'state' is undefined
```

In fact every sentence with state.state or slot.name generating error.

**Comment by skynetua** [comment]
Fixed in https://github.com/home-assistant/intents/pull/1027
