### ISSUE TITLE
German language leader

### ISSUE THREAD

**Issue by Scorpoon** [home-assistant/intents#72]
Hi,

i'm available for reviewing, merging and also contributing to intents in German.

Best regards
Thomas

**Comment by synesthesiam** [comment]
Thanks @Scorpoon! I'll contact you soon :)

**Comment by mib1185** [comment]
if you need a representative ✋

**Comment by osworx** [comment]
Hello,

having experience in translating / creating German language files to several big projects the last 20 years (and maintaining them also afterwards), I would be happy to help.
Either as leader or contributor or whatever is needed ..

br
mic

**Comment by N3rdix** [comment]
Also happy to help out, have some years of experience from multiple development projects

**Comment by Scorpoon** [comment]
> Hello,
> 
> having experience in translating / creating German language files to several big projects the last 20 years (and maintaining them also afterwards), I would be happy to help.
> Either as leader or contributor or whatever is needed ..
> 
> br
> mic

Btw, hello from district LB 😅

**Comment by TheDK** [comment]
Happy to help in reviewing and adding as well…

**Comment by easterapps** [comment]
Happy to contribute as well

**Comment by synesthesiam** [comment]
Discussion moved here: https://github.com/home-assistant/intents/discussions/347
