### ISSUE TITLE
Some more natural responses could be implemented

### ISSUE THREAD

**Issue by relust** [home-assistant/intents#737]
I was wondering if some more natural responses could be implemented. For example, for each execution word in the sentences, there should correspond a word, an expression to answers such as: “turn on” → “turned on” (“turn on kithcen light” → "turned on kitchen light"), "switch" →  "switched", "change" → "changed", "open" →  "opened", etc. For example, in Romanian it would be much more natural to say “aprinde lumina din bucătărie” and it response “am aprins lumina din bucătărie” instead of “am pornit lumina din bucătărie”. Or in English, if I say "swithc on kitchen light", the answer should be "switched on kitchen light" and not "turned on kitchen light". It could only use “turn on” and “turn off” intents and, in responses, only change the response word, adapted to the word with which the request was made. I think it would be easier to define related words for sentences and responses than to define sentences and responses for each device type (light, fan, cover etc).

**Comment by alessandroias** [comment]
I think it's too complex for the moment, while a great way to make the assistant more natural could be to replace "turned on {name}" with " ""I've turned on {name}". It's really easy, but it makes a lot of difference!

**Comment by synesthesiam** [comment]
It really depends on the client, whether it's a chat interface like in HA or something with a much smaller screen. We may need to split responses into "short" and "long" forms.

Of course, it's always possible to override the default responses in your HA config.

**Comment by relust** [comment]
Today I tested the beta version and I am very pleasantly impressed. I
would be happy if for the next step a correlation could be made
between the words used in sentences and those used in responses. It
doesn't take up more space to answer for example "switch on kitchen
light" with "switched on kitchen light" than with "turned on kitchen
light". If it always gives the same kind of response no matter how the
request is made, it seems a bit robotic. But for now it is very good
what has been done.


În joi, 26 ian. 2023 la 19:18, Michael Hansen ***@***.***> a
scris:

**Comment by synesthesiam** [comment]
This might be something to bring up here: https://github.com/home-assistant/intents/discussions/871
