### ISSUE TITLE
" vs ' vs 

### ISSUE THREAD

**Issue by Robin-St** [home-assistant/intents#817]
What is the preferred way to encapsulate sentences? With a ", ' or nothing? The documentation https://github.com/home-assistant/intents/tree/main/sentences has mostly " but some example of ' and the PR that added responses seems to have changed a lot of " to '. Having neither seems to work too.

Is there any need to have a standard? If so, which one should be used? :)

**Comment by synesthesiam** [comment]
YAML linting is done automatically now with prettier
