### ISSUE TITLE
Getting state of entities

### ISSUE THREAD

**Issue by Paradox8** [home-assistant/intents#857]
Something which I regularly ask my voice assistant is "What windows are open" which then responds with the names of every window open in the house. I use this because if I'm going to turn the AC on, I'll ask this so I know which rooms to go and shut windows.
Support for this kind of question would be fantastic.

**Comment by domoritz** [comment]
Similarly "is the kitchen light on" or "is the garage open?" should be supported.

**Comment by philpownall** [comment]
I couldn't agree more - it is **essential** that Home Assistant Assist supports getting the current state of any entity - even the examples using HassGetState do not work at present.  As a limited sight person with 7 devices (computers/phones,etc), 4 temperature/humidity sensors, 5 ESP32 micro-controllers, and several window and door sensors it is vital to have audible feedback, even when the internet is off, and I'm not going to create custom intents and intent_scripts for over 100 entities.

**Comment by synesthesiam** [comment]
The `HassGetState` intent is now supported in HA, and the sentences for it will be in the next release: https://developers.home-assistant.io/blog/2023/02/09/hassgetstate

**Comment by philpownall** [comment]
That's great - I hope the sentences work better than in the example, which I can't get to work at all.  The clue is in "This relies on having entity names (or aliases) set up just right, of course".  

On the other hand, I just spent a pleasant few hours experimenting with the custom intents, getting an Aussie (I'm Canadian) to respond to my questions:  Here is the fragment of my configuration.yaml  

```
conversation:
  intents:
    MyGetTemp:
      - "What is the temperature in [the] {area}"
      - "Tell me [the] temperature in [the] {area}"
      - "How hot is it in [the] {area}"
      
intent_script:
  MyGetTemp:
    action:
      service: "tts.cloud_say"
      data:
        options:
          gender: male
        language: en-AU
        cache: false
        entity_id: "media_player.upmpd_pizerow1_upnp_av"
        message: >
          {% if area == 'living_room' %}
            {% set mytemp = states('sensor.living_room_6062_temperature') %}
          {% elif area == 'kitchen' %}
            {% set mytemp = states('sensor.kitchen_64e0_temperature') %}
          {% elif area == 'bedroom' %}
            {% set mytemp = states('sensor.bedroom_temperature') %}
          {% elif area == 'bathroom' %}
            {% set mytemp = states('sensor.bathroom_541d_temperature') %}
          {% else %}
            {% set mytemp = 'unavailable' %}
          {% endif %}
          {% if mytemp == 'unavailable' %} 
            The temperature in the {{area}} is not available at present
          {% else %}
            It is {{ mytemp | int }} degrees C
          {% endif %}

```
