### ISSUE TITLE
Can't set language to Bulgarian/ iOS

### ISSUE THREAD

**Issue by ddppddpp** [home-assistant/intents#906]
The Assist Button shortcut on iOS doesn't list Bulgarian as a language option.
iOS 16.3
HA 2023.2.1
Supervisor 2023.01.1
OS 9.5
HA Companion 2023.2(2023.443)
![IMG_65649E156049-1](https://user-images.githubusercontent.com/45116849/216781581-a0f2fd72-9f3f-427a-aa9f-faaf277625d7.jpeg)

**Comment by synesthesiam** [comment]
Does Siri support Bulgarian?

**Comment by ddppddpp** [comment]
naaah it doesn’t 😭

**Comment by synesthesiam** [comment]
If more people can contribute to Bulgarian in Common Voice, I can train a model: https://commonvoice.mozilla.org/en/languages

**Comment by ddppddpp** [comment]
Even if you do, and I do wish you success, I can't see Apple adopting it...
Which makes using Assist via Mac/iOS/Siri in languages not supported by Apple a bit impractical.

**Comment by synesthesiam** [comment]
Yeah, Apple would never adopt an outside model. But I'm thinking more for the open source voice community in general. The hope is to run local speech to text in Home Assistant.
