### ISSUE TITLE
Hebrew language leader

### ISSUE THREAD

**Issue by leranp** [home-assistant/intents#91]
Hi,
I'm willing to be the leader of the Hebrew language.

**Comment by thecode** [comment]
@leranp please contact me on discord, we have a team working on Hebrew with a potential leader there, lets discuss it.

thecode#6829

**Comment by synesthesiam** [comment]
@thecode Would you like me to create empty Hebrew templates here, or wait for a PR?

**Comment by thecode** [comment]
> @thecode Would you like me to create empty Hebrew templates here, or wait for a PR?

We have an open PR https://github.com/home-assistant/intents/pull/32 to add Hebrew, I think it is basically a template, if you think it is better to make empty template first, please do.

@leranp & @haim-b please create a PR to add yourself as language leaders, here is an example of the files needs to be updated: https://github.com/home-assistant/intents/commit/2166a0a26826f1983aaa38561a6a29937334a925

**Comment by synesthesiam** [comment]
Looks like the toggle intent needs to be deleted. I didn't see the PR since it got converted to a draft for some reason.

**Comment by leranp** [comment]
> > @thecode Would you like me to create empty Hebrew templates here, or wait for a PR?
> 
> We have an open PR https://github.com/home-assistant/intents/pull/32 to add Hebrew, I think it is basically a template, if you think it is better to make empty template first, please do.
> 
> @leranp & @haim-b please create a PR to add yourself as language leaders, here is an example of the files needs to be updated: https://github.com/home-assistant/intents/commit/2166a0a26826f1983aaa38561a6a29937334a925

Done #123

**Comment by haim-b** [comment]
> leranp please contact me on discord, we have a team working on Hebrew with a potential leader there, lets discuss it.

Added to my PR on top of @leranp 's
