### ISSUE TITLE
add text to german for asking temperature

### ISSUE THREAD

**Issue by renarena** [home-assistant/intents#932]
https://github.com/home-assistant/intents/blob/main/sentences/de/climate_HassClimateGetTemperature.yaml

```
          - "Wie hoch ist die Temperatur vom Thermostat <area>"
          - "Wie warm ist es <area>"
```
change this to something like
 ```
         - "Wie (hoch|tief) ist die Temperatur vom Thermostat <area>"
          - "Wie (warm|kalt) ist es <area>"
and doesnt we need something like` [in|im] <area>`
```
How can i get the temperature from a sensor? My thermostats dont know the current temperature.

**Comment by synesthesiam** [comment]
Please continue discussion here: https://github.com/home-assistant/intents/discussions/348
