### ISSUE TITLE
Move cover sentences into own file

### ISSUE THREAD

**Issue by piitaya** [home-assistant/intents#959]
Should we move cover sentences into its own files `cover_HassTurnOn` and `cover_HassTurnOff`? 
We already dedicated file for lights and fans.

**Comment by synesthesiam** [comment]
Yes, I will be doing this for the English sentences soon.

**Comment by TheFes** [comment]
> Yes, I will be doing this for the English sentences soon.

Should we all do this ourselves, of will you do one big change as balloob tried to do?

**Comment by synesthesiam** [comment]
One big change has gone through :D
