### ISSUE TITLE
Assist fails to turn on/off switch entity because it tries to act on sensor with same name

### ISSUE THREAD

**Issue by kompre** [home-assistant/intents#977]
hello,

I have a sensor and switch entities both named "ingresso". This was not an ambiguity because they belong to different domains, so that one is called `sensor.ingresso` and the other `switch.ingresso`.

When I tell Assist to turn on/off the switch entity (e.g. `turn on ingresso`), Assist will try to turn on the sensor instead of the swicth and will, of course, fail. It also fails silently because Assist will respond saying the ingresso has been turned on, but the log says that such action is not supported for sensor entity.

> Logger: homeassistant.components.homeassistant
Source: components/homeassistant/__init__.py:117
Integration: Home Assistant Core Integration (documentation, issues)
First occurred: 16:42:27 (1 occurrences)
Last logged: 16:42:27
The service homeassistant.turn_on does not support entities sensor.ingresso

This can be fixed by changing the name of the sensor from `ingresso` to `ingresso_`

I can't think an instance where a sensor can be acted upon, to my knowledge sensors can only be read by user or automation, therefore I think that they should be filtered out if an action could not be applied to such an entity.

**Comment by synesthesiam** [comment]
The English on/off sentences now exclude the `sensor` domain
