### ISSUE TITLE
Entity name is not parsed

### ISSUE THREAD

**Issue by schizza** [home-assistant/intents#980]
While making GetState as in #979 

In fixtures we have defined entity as:  `  - name: (Lamp(a|y|u)|lampičk(a|y|u)|světl(o|a)) v ložnici`

But in test we have AssertionError, while the name is not parsed correctly:

```
 AssertionError: Incorrect response for: která světla jsou zapnutá?
E                   assert '(Lamp(a|y|u)|lampičk(a|y|u)|světl(o|a)) v ložnici, předsíň' in {'lampička v ložnici, předsíň'}

```

**Comment by LubosKadasi** [comment]
I think it also applies to area.

**Comment by synesthesiam** [comment]
Should be fixed by: https://github.com/home-assistant/intents/pull/1076
