### ISSUE TITLE
HassGetState - translation issue

### ISSUE THREAD

**Issue by svarthvitt** [home-assistant/intents#982]
In translating HassGetState, I run into the issue below (translated):
Test: "Is the bedroom lamp on?"
Result: "No, the bedroom lamp is on"

 The on_off_states (in: "på" /  out: "on") works for the test, but not for the response query. 

**Result from testing**
`@svarthvitt ➜ /workspaces/intents (HassGetState.yaml-translation) $ python3 -m script.intentfest parse --language nb --sentence 'er soveromlampe på?'
{
  "text": "er soveromlampe på?",
  "match": true,
  "intent": "HassGetState",
  "slots": {
    "name": "Soveromlampe",
    "state": "on"
  },
  "response_key": "one_yesno",
  "response": "Nei, soveromlampe er på"
}`

Am I doing anything wrong? 

@LaStrada: FYI

**Comment by svarthvitt** [comment]
I see [NL] and @TheFes has a good way to solve this issue. I can adapt this for [NB].
https://github.com/home-assistant/intents/blob/main/responses/nl/HassGetState.yaml

@synesthesiam Will there be any guidance on best practices to avoid languages drifting apart on the technical side?

Thanks

**Comment by TheFes** [comment]
In my chats with @balloob (as he is also speaking Dutch he usually performs the reviews of my changes) he referred to setting up a style guide for the responses.

**Comment by synesthesiam** [comment]
Merged this PR to help: https://github.com/home-assistant/intents/pull/1001
